SELECT AVG(SPEED)
FROM pc;

SELECT MAKER, AVG(SCREEN)
FROM laptop LEFT JOIN product on laptop.MODEL == product.MODEL
GROUP BY MAKER;

SELECT AVG(SPEED)
FROM laptop
WHERE PRICE > 1000;

SELECT HD, AVG(PRICE)
FROM pc
GROUP BY HD;

SELECT SPEED,AVG(PRICE)
FROM pc
WHERE SPEED >= 500
GROUP BY SPEED;

SELECT AVG(PRICE)
FROM pc LEFT JOIN product ON pc.MODEL == product.MODEL
WHERE MAKER == 'A';



SELECT MAKER
FROM pc INNER JOIN product ON pc.MODEL == product.MODEL
GROUP BY MAKER
HAVING COUNT(MAKER)>=3;

SELECT MAKER, MAX(PRICE)
FROM pc INNER JOIN product ON pc.MODEL == product.MODEL;

SELECT MAKER,AVG(pc.HD)
FROM pc INNER JOIN product ON pc.MODEL == product.MODEL
GROUP BY MAKER
HAVING MAKER IN (SELECT MAKER FROM printer INNER JOIN product ON printer.MODEL == product.MODEL);
