SELECT AVG(SPEED)
FROM pc;

SELECT MAKER, AVG(SCREEN)
FROM laptop LEFT JOIN product on laptop.MODEL == product.MODEL
GROUP BY MAKER;

SELECT AVG(SPEED)
FROM laptop
WHERE PRICE > 1000;

SELECT HD, AVG(PRICE)
FROM pc
GROUP BY HD;

SELECT SPEED,AVG(PRICE)
FROM pc
WHERE SPEED >= 500
GROUP BY SPEED;

SELECT AVG(PRICE)
FROM pc LEFT JOIN product ON pc.MODEL == product.MODEL
WHERE MAKER == 'A';




