SELECT ADDRESS
FROM STUDIO
WHERE NAME == "MGM";

SELECT BIRTHDATE
FROM MOVIESTAR
WHERE NAME=="Kim Basinger";

SELECT NAME 
FROM MOVIEEXEC
WHERE NETWORTH > 10000000;

SELECT NAME
FROM MOVIESTAR
WHERE GENDER == 'M' OR ADDRESS == "Prefect Rd";

INSERT INTO MOVIESTAR
VALUES("Zahari Baharov","Mladost3",'M',"1989-02-24");

DELETE FROM STUDIO
WHERE ADDRESS LIKE "%5%";

UPDATE MOVIE
SET STUDIONAME = 'Fox'
WHERE TITLE LIKE "%star%";