SELECT NAME 
FROM (MOVIESTAR LEFT JOIN STARSIN ON NAME = STARNAME) LEFT JOIN MOVIE ON MOVIETITLE = TITLE
WHERE TITLE == "Terms of Endearment";

SELECT NAME
FROM (MOVIESTAR LEFT JOIN STARSIN ON NAME = STARNAME) LEFT JOIN MOVIE ON MOVIETITLE = TITLE
WHERE STUDIONAME == 'MGM' AND YEAR == 1995;

/*ALTER TABLE STUDIO
ADD COLUMN PRESIDENT VARCHAR(55);
*/
UPDATE STUDIO
SET PRESIDENT = 'Marco Polo'
WHERE NAME == 'MGM';

SELECT PRESIDENT
FROM STUDIO
WHERE NAME == 'MGM';

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE == 'Gone With the Wind');